from __future__ import annotations

from types import SimpleNamespace

import pytest


def test_task_state_source_renders_explicit_state_ref():
    from app.context_engine.sources.task_state import _render_state_ref

    rendered = _render_state_ref(
        {
            "test_plan_generation_instruction": "generate a test plan",
            "output_contract": "json only",
            "ai_fields": [
                {
                    "field": "overview",
                    "title": "Overview",
                    "section_id": "sec_1",
                    "level": 1,
                    "table_schemas": [{"headers": ["case", "expected"]}],
                }
            ],
            "template_headings": ["1 Overview"],
            "table_fields": ["case|expected"],
        }
    )

    assert "explicit_state_ref" in rendered
    assert "field=overview" in rendered
    assert "table_headers=case, expected" in rendered
    assert "json only" not in rendered


def test_frozen_retrieval_bundle_keeps_source_and_history_hints() -> None:
    from app.tools.test_plan_generator_tool import _retrieval_bundle_records

    records = _retrieval_bundle_records(
        {
            "frozen": True,
            "retrieval_round": 2,
            "project_rag": {
                "hits": [
                    {
                        "evidence_id": "project_chunk_1",
                        "title": "Previous requirement",
                        "content": "A project-specific acceptance rule.",
                        "version_hint": "v1.2",
                        "date_hint": "2026-09-30T10:00:00",
                    }
                ]
            },
            "company_rag": {
                "hits": [
                    {
                        "chunk_id": "company_chunk_1",
                        "title": "Company practice",
                        "snippet": "A company-level test-plan convention.",
                    }
                ]
            },
        }
    )

    assert len(records) == 2
    assert records[0]["retrieval_source"] == "project_rag"
    assert "Document version/date hint: v1.2 / 2026-09-30T10:00:00" in records[0]["content"]
    assert records[1]["retrieval_source"] == "company_rag"


@pytest.mark.asyncio
async def test_test_plan_generator_uses_context_invoker_when_mig_generate_enabled():
    import app.common.prompt_builder as prompt_builder_module
    from app.tools.test_plan_generator_tool import TestPlanGeneratorTool

    class _Resolver:
        def evaluate(self, key):
            assert key in {"CONTEXT_ENGINE_AGENT_ENABLED", "MIG_GENERATE"}
            return key in {"CONTEXT_ENGINE_AGENT_ENABLED", "MIG_GENERATE"}

    class _Bridge:
        available = True

        async def generate(self, **kwargs):
            self.kwargs = kwargs
            return SimpleNamespace(value='{"overview": "generated by bridge"}')

    bridge = _Bridge()
    class _LegacyPromptMustNotRun:
        def __init__(self, *args, **kwargs):
            raise AssertionError("TestPlanGeneratorTool must not construct PromptBuilder")

    original_prompt_builder = prompt_builder_module.PromptBuilder
    prompt_builder_module.PromptBuilder = _LegacyPromptMustNotRun
    ctx = SimpleNamespace(
        task_id="task_1",
        task_internal_id=1,
        conversation_internal_id=2,
        user_internal_id=3,
        task_flag_resolver=_Resolver(),
        context_llm_invoker=bridge,
        knowledge_search_result={
            "source": "company_rag",
            "query": "payment idempotency",
            "hit_count": 1,
            "degraded": False,
            "similar_projects": [
                {
                    "name": "payment rules",
                    "snippet": "UNIQUE_BRIDGE_KB_SNIPPET",
                }
            ],
        },
        requirement_analysis={"text_content": "payment requirement text"},
        template_structure={
            "sections": [{"title": "1 Overview", "children": []}],
            "generation_config": {
                "ai_fields": [
                    {
                        "field": "overview",
                        "title": "Overview",
                        "section_id": "sec_1",
                        "level": 1,
                    }
                ],
                "keep_sections": [],
                "manual_sections": [],
                "section_bindings": [],
            },
        },
        test_plan_content=None,
    )

    try:
        result = await TestPlanGeneratorTool().run({}, ctx)
    finally:
        prompt_builder_module.PromptBuilder = original_prompt_builder

    assert result["success"] is True
    assert bridge.kwargs["call_site"] == "test_plan.generate.outline"
    assert bridge.kwargs["runtime_context"] is ctx
    assert "UNIQUE_BRIDGE_KB_SNIPPET" not in bridge.kwargs["current_goal"]
    assert bridge.kwargs["current_goal"] == "请根据需求文档和模板结构生成测试方案内容。"
    assert bridge.kwargs["task_state_ref"]["ai_fields"][0]["field"] == "overview"
    assert "output_contract" not in bridge.kwargs["task_state_ref"]
    assert "Keys must exactly match" in bridge.kwargs["output_contract"]
    assert '"overview"' in bridge.kwargs["output_contract"]
    assert "ALLOWED JSON FIELDS" in bridge.kwargs["system_prompt"]
    assert "overview: Overview" in bridge.kwargs["system_prompt"]
    assert "never wrap it in table, content, title, value, or data" in bridge.kwargs["system_prompt"]
    evidence = bridge.kwargs["task_state_ref"]["context_evidence"]
    assert evidence["parsed_documents"][0]["content"] == "payment requirement text"
    assert evidence["template_sections"][0]["title"] == "1 Overview"
    assert ctx.test_plan_content is not None


@pytest.mark.asyncio
async def test_malformed_non_truncated_bridge_output_runs_tool_recovery_protocol():
    """CE must pass raw malformed output to the generator's repair pipeline."""
    from app.tools.test_plan_generator_tool import TestPlanGeneratorTool

    class _Resolver:
        def evaluate(self, key):
            return key in {"CONTEXT_ENGINE_AGENT_ENABLED", "MIG_GENERATE"}

    class _Bridge:
        available = True

        def __init__(self):
            self.calls = []

        async def generate(self, **kwargs):
            self.calls.append(kwargs)
            mode = kwargs["task_state_ref"].get("generation_mode")
            if mode == "json_syntax_recovery_outline":
                return SimpleNamespace(value=(
                    '{"terminology":{},"cross_cutting":[],'
                    'chapter_summaries":{"overview":"summary",'
                    '"scope":"summary","strategy":"summary"}}'
                ))
            if mode == "json_syntax_recovery_batch":
                fields = kwargs["task_state_ref"]["batch_fields"]
                if fields == ["overview", "scope"]:
                    return SimpleNamespace(value=(
                        '{"overview":"Payment release overview",'
                        '"scope":[[{"module":"payment"}]]}'
                    ))
                return SimpleNamespace(value='{"strategy":"Risk-based testing"}')
            # Validly closed but syntactically invalid: this is not truncation.
            return SimpleNamespace(value='{"overview":"bad",}')

    bridge = _Bridge()
    ctx = SimpleNamespace(
        task_id="task_malformed_json",
        task_internal_id=61,
        conversation_internal_id=62,
        user_internal_id=63,
        task_flag_resolver=_Resolver(),
        context_llm_invoker=bridge,
        knowledge_search_result={},
        requirement_analysis={"text_content": "payment requirement"},
        template_structure={
            "sections": [
                {"title": "Overview", "children": []},
                {"title": "Scope", "children": []},
                {"title": "Strategy", "children": []},
            ],
            "generation_config": {
                "ai_fields": [
                    {"field": "overview", "title": "Overview", "section_id": "overview"},
                    {
                        "field": "scope",
                        "title": "Scope",
                        "section_id": "scope",
                        "table_schemas": [{"headers": ["module"]}],
                    },
                    {"field": "strategy", "title": "Strategy", "section_id": "strategy"},
                ],
                "keep_sections": [],
                "manual_sections": [],
                "section_bindings": [],
            },
        },
        test_plan_content=None,
    )

    result = await TestPlanGeneratorTool().run({}, ctx)

    assert result["success"] is True
    recovery = result["data"]["generation_recovery"]
    assert recovery["kind"] == "json_syntax_outline_batch"
    assert recovery["repair_attempted"] is True
    assert recovery["json_error_position"] == {"line": 1, "column": 18}
    assert recovery["recovery_round"] == 2
    assert recovery["status"] == "recovered"
    assert recovery["completed_batches"] == 2
    assert recovery["successful_field_count"] == 3
    assert bridge.calls[0]["llm_task_profile"].name == "test_plan_generation_raw"
    assert bridge.calls[1]["task_state_ref"]["generation_mode"] == "json_syntax_repair"
    assert bridge.calls[1]["llm_task_profile"].name == "test_plan_generation_json_repair_raw"
    assert bridge.calls[2]["task_state_ref"]["generation_mode"] == "json_syntax_recovery_outline"
    assert bridge.calls[3]["task_state_ref"]["batch_fields"] == ["overview", "scope"]
    assert bridge.calls[4]["task_state_ref"]["batch_fields"] == ["strategy"]


@pytest.mark.asyncio
async def test_targeted_regeneration_keeps_template_rules_in_ce_system_prompt():
    """Repair evidence may be user-role content; schema rules may not be."""
    from app.tools.test_plan_regen_tool import TestPlanRegenTool

    class _Resolver:
        def evaluate(self, key):
            return key in {"CONTEXT_ENGINE_AGENT_ENABLED", "MIG_GENERATE"}

    class _Bridge:
        available = True

        async def generate(self, **kwargs):
            self.kwargs = kwargs
            return SimpleNamespace(value={"scope": [{"module": "payment"}]})

    bridge = _Bridge()
    ctx = SimpleNamespace(
        task_flag_resolver=_Resolver(),
        context_llm_invoker=bridge,
        user_internal_id=3,
        conversation_internal_id=2,
        task_id="task_regen",
        task_internal_id=1,
        test_plan_content={},
        review_result={},
    )
    target = {
        "field": "scope",
        "cfg": {
            "field": "scope",
            "title": "Scope",
            "section_id": "scope",
            "table_schemas": [{"headers": ["module"]}],
        },
    }

    raw = await TestPlanRegenTool()._generate_regen_json(
        "repair evidence for scope",
        target_batch=[target],
        context=ctx,
        use_mock=False,
    )

    assert '"scope"' in raw
    assert bridge.kwargs["call_site"] == "test_plan.repair.regenerate"
    assert "ALLOWED JSON FIELDS" in bridge.kwargs["system_prompt"]
    assert "scope: Scope" in bridge.kwargs["system_prompt"]
    assert "never wrap it in table, content, title, value, or data" in bridge.kwargs["system_prompt"]


@pytest.mark.asyncio
async def test_truncated_one_shot_switches_to_ce_outline_and_validated_batches():
    """The exceptional truncation route is generator-owned, not RepairAgent-owned."""
    from app.tools.test_plan_generator_tool import TestPlanGeneratorTool

    class _Resolver:
        def evaluate(self, key):
            return key in {"CONTEXT_ENGINE_AGENT_ENABLED", "MIG_GENERATE"}

    class _Bridge:
        available = True

        def __init__(self):
            self.calls = []

        async def generate(self, **kwargs):
            self.calls.append(kwargs)
            mode = kwargs["task_state_ref"].get("generation_mode")
            if mode == "json_truncation_recovery_outline":
                return SimpleNamespace(value=(
                    '{"terminology":{"payment":"payment"},'
                    '"cross_cutting":["idempotency"],'
                    '"chapter_summaries":{"overview":"summary",'
                    '"scope":"summary","strategy":"summary"}}'
                ))
            if mode == "json_truncation_recovery_batch":
                fields = kwargs["task_state_ref"]["batch_fields"]
                if fields == ["overview", "scope"]:
                    return SimpleNamespace(value=(
                        '{"overview":"Payment release overview",'
                        '"scope":[[{"module":"payment"}]]}'
                    ))
                return SimpleNamespace(value='{"strategy":"Risk-based testing"}')
            # Simulate the provider cutting the original full JSON before its
            # outer object closes.
            return SimpleNamespace(value='{"overview":"partial output"')

    bridge = _Bridge()
    ctx = SimpleNamespace(
        task_id="task_truncated",
        task_internal_id=41,
        conversation_internal_id=42,
        user_internal_id=43,
        task_flag_resolver=_Resolver(),
        context_llm_invoker=bridge,
        knowledge_search_result={},
        requirement_analysis={"text_content": "payment requirement"},
        template_structure={
            "sections": [
                {"title": "Overview", "children": []},
                {"title": "Scope", "children": []},
                {"title": "Strategy", "children": []},
            ],
            "generation_config": {
                "ai_fields": [
                    {"field": "overview", "title": "Overview", "section_id": "overview"},
                    {
                        "field": "scope",
                        "title": "Scope",
                        "section_id": "scope",
                        "table_schemas": [{"headers": ["module"]}],
                    },
                    {"field": "strategy", "title": "Strategy", "section_id": "strategy"},
                ],
                "keep_sections": [],
                "manual_sections": [],
                "section_bindings": [],
            },
        },
        test_plan_content=None,
    )

    result = await TestPlanGeneratorTool().run({}, ctx)

    assert result["success"] is True
    assert result["data"]["generated_sections"] == 3
    assert result["data"]["generation_recovery"]["status"] == "recovered"
    assert "schema_issues" not in result["data"]
    assert [call["call_site"] for call in bridge.calls] == [
        "test_plan.generate.outline",
        "test_plan.generate.outline",
        "test_plan.generate.batch",
        "test_plan.generate.batch",
    ]
    assert bridge.calls[1]["llm_task_profile"].name == "test_plan_generation_outline"
    assert bridge.calls[2]["llm_task_profile"].name == "test_plan_generation_batch"
    assert "scope" in bridge.calls[2]["output_contract"]
    assert "strategy" not in bridge.calls[2]["output_contract"]
    assert "scope: Scope" in bridge.calls[2]["system_prompt"]
    assert "strategy: Strategy" not in bridge.calls[2]["system_prompt"]


@pytest.mark.asyncio
async def test_failed_truncation_batch_defers_to_repair_agent_safety_net():
    """A failed exceptional recovery remains recoverable rather than killing the task."""
    from app.tools.test_plan_generator_tool import TestPlanGeneratorTool

    class _Resolver:
        def evaluate(self, key):
            return key in {"CONTEXT_ENGINE_AGENT_ENABLED", "MIG_GENERATE"}

    class _Bridge:
        available = True

        async def generate(self, **kwargs):
            mode = kwargs["task_state_ref"].get("generation_mode")
            if mode == "json_truncation_recovery_outline":
                return SimpleNamespace(value=(
                    '{"terminology":{},"cross_cutting":[],'
                    '"chapter_summaries":{"overview":"summary"}}'
                ))
            if mode == "json_truncation_recovery_batch":
                # Valid JSON but invalid for the server-derived batch contract.
                return SimpleNamespace(value='{"unexpected":"field"}')
            return SimpleNamespace(value='{"overview":"partial output"')

    ctx = SimpleNamespace(
        task_id="task_truncated_batch_failure",
        task_internal_id=51,
        conversation_internal_id=52,
        user_internal_id=53,
        task_flag_resolver=_Resolver(),
        context_llm_invoker=_Bridge(),
        knowledge_search_result={},
        requirement_analysis={"text_content": "payment requirement"},
        template_structure={
            "sections": [{"title": "Overview", "children": []}],
            "generation_config": {
                "ai_fields": [{"field": "overview", "section_id": "overview"}],
                "keep_sections": [],
                "manual_sections": [],
                "section_bindings": [],
            },
        },
        test_plan_content=None,
    )

    result = await TestPlanGeneratorTool().run({}, ctx)

    assert result["success"] is True
    assert result["warnings"][0]["code"] == "JSON_SEVERE_TRUNCATION"
    recovery = result["data"]["generation_recovery"]
    assert recovery["outline_batch_attempt"]["failure"] == "batch_contract_invalid"
    assert result["data"]["schema_issues"]


@pytest.mark.asyncio
async def test_test_plan_generator_blocks_when_frozen_ce_flag_is_missing():
    from app.tools.test_plan_generator_tool import TestPlanGeneratorTool

    class _Bridge:
        available = True
        calls = 0

        async def generate(self, **kwargs):
            self.calls += 1
            return SimpleNamespace(value='{"overview": "must not run"}')

    bridge = _Bridge()
    ctx = SimpleNamespace(
        task_id="task_without_manifest",
        task_internal_id=1,
        conversation_internal_id=2,
        user_internal_id=3,
        task_flag_resolver=None,
        context_llm_invoker=bridge,
        requirement_analysis={"text_content": "requirement"},
        template_structure={
            "sections": [{"title": "1 Overview", "children": []}],
            "generation_config": {"ai_fields": [{"field": "overview", "section_id": "sec_1"}]},
        },
    )

    result = await TestPlanGeneratorTool().run({}, ctx)

    assert result["success"] is False
    assert result["error"]["code"] == "MIGRATION_CONTEXT_REQUIRED"
    assert bridge.calls == 0


@pytest.mark.asyncio
async def test_long_requirement_extracts_every_chunk_before_final_generation(monkeypatch):
    from app.context_engine.evidence.requirement_pipeline import RequirementEvidencePreparer
    import app.tools.test_plan_generator_tool as generator_module
    from app.tools.test_plan_generator_tool import TestPlanGeneratorTool

    original_preparer = RequirementEvidencePreparer
    monkeypatch.setattr(
        generator_module,
        "RequirementEvidencePreparer",
        lambda: original_preparer(
            direct_limit_tokens=80,
            chunk_limit_tokens=48,
            estimate=len,
        ),
    )

    class _Resolver:
        def evaluate(self, key):
            return key in {"CONTEXT_ENGINE_AGENT_ENABLED", "MIG_GENERATE"}

    class _Bridge:
        available = True

        def __init__(self):
            self.calls = []

        async def generate(self, **kwargs):
            self.calls.append(kwargs)
            if kwargs["call_site"] == "test_plan.requirement.extract":
                chunk_id = kwargs["task_state_ref"]["chunk_id"]
                return SimpleNamespace(value=f"{chunk_id} extracted requirement ledger")
            return SimpleNamespace(value='{"overview": "generated from complete ledger"}')

    bridge = _Bridge()
    requirement_text = "\n\n".join(
        f"REQ-{index:03d} exact requirement detail {index}"
        for index in range(16)
    )
    ctx = SimpleNamespace(
        task_id="task_long",
        task_internal_id=11,
        conversation_internal_id=12,
        user_internal_id=13,
        task_flag_resolver=_Resolver(),
        context_llm_invoker=bridge,
        knowledge_search_result={},
        requirement_analysis={
            "source_ref": "file_long_requirement",
            "document_name": "long-requirements.md",
            "text_content": requirement_text,
        },
        template_structure={
            "sections": [{"title": "1 Overview", "children": []}],
            "generation_config": {
                "ai_fields": [
                    {
                        "field": "overview",
                        "title": "Overview",
                        "section_id": "sec_1",
                        "level": 1,
                    }
                ],
                "keep_sections": [],
                "manual_sections": [],
                "section_bindings": [],
            },
        },
        test_plan_content=None,
    )

    result = await TestPlanGeneratorTool().run({}, ctx)

    assert result["success"] is True
    extraction_calls = [
        call for call in bridge.calls
        if call["call_site"] == "test_plan.requirement.extract"
    ]
    final_call = bridge.calls[-1]
    assert len(extraction_calls) > 1
    assert final_call["call_site"] == "test_plan.generate.outline"
    evidence = final_call["task_state_ref"]["context_evidence"]
    assert evidence["coverage_manifest"]["coverage_complete"] is True
    assert evidence["coverage_manifest"]["source_characters"] == len(requirement_text)
    assert len(evidence["parsed_documents"]) == len(extraction_calls)
    assert final_call["task_state_ref"]["conversation_policy"] == {
        "recent_complete_turns": 6,
        "include_summary": False,
        "protect_recent_turns": True,
    }
    assert "REQ-000" in extraction_calls[0]["current_goal"]
    assert "REQ-015" in extraction_calls[-1]["current_goal"]


@pytest.mark.asyncio
async def test_generator_defers_failed_schema_recovery_to_repair_agent(monkeypatch):
    from app.tools.test_plan_generator_tool import TestPlanGeneratorTool
    from app.tools.test_plan_regen_tool import TestPlanRegenTool

    class _Resolver:
        def evaluate(self, key):
            return key in {"CONTEXT_ENGINE_AGENT_ENABLED", "MIG_GENERATE"}

    class _Bridge:
        available = True

        async def generate(self, **kwargs):
            return SimpleNamespace(
                value='{"scope":[[{"module":"payment","unexpected":"column"}]]}'
            )

    async def failed_regenerate(self, inputs, context, retry_context=None):  # noqa: ARG001
        return {
            "success": False,
            "data": {"partial_success": True, "unresolved_section_ids": ["scope"]},
        }

    monkeypatch.setattr(TestPlanRegenTool, "run", failed_regenerate)
    ctx = SimpleNamespace(
        task_id="task_schema_deferred",
        task_internal_id=31,
        conversation_internal_id=32,
        user_internal_id=33,
        task_flag_resolver=_Resolver(),
        context_llm_invoker=_Bridge(),
        knowledge_search_result={},
        requirement_analysis={"text_content": "payment requirement"},
        template_structure={
            "sections": [{"title": "Scope", "children": []}],
            "generation_config": {
                "ai_fields": [{
                    "field": "scope",
                    "title": "Scope",
                    "section_id": "scope",
                    "table_schemas": [{"headers": ["module"]}],
                }],
                "keep_sections": [],
                "manual_sections": [],
                "section_bindings": [],
            },
        },
        test_plan_content=None,
    )

    result = await TestPlanGeneratorTool().run({}, ctx)

    assert result["success"] is True
    assert result["data"]["repair_required"] is True
    assert result["data"]["schema_issues"]
    assert result["warnings"][0]["code"] == "SCHEMA_RECOVERY_DEFERRED"
